@startuml
[*] --> SLEEPING
SLEEPING: do/sleep for 1 second
SLEEPING --> PROCESSING_RECEIVE : 1 second elapsed
MOVING: exit/send arrived message
SLEEPING --> [*] : on kill

MOVING --> SLEEPING : time passed
MOVING --> [*] : on kill

PROCESSING_RECEIVE --> SLEEPING : finished processing message
PROCESSING_RECEIVE: entry/check for move to message
PROCESSING_RECEIVE: do/process message message
PROCESSING_RECEIVE --> [*] : on kill
MOVING --> DOOR_OPENING : is moving
DOOR_OPENING --> SLEEPING : 1s elapsed
PROCESSING_RECEIVE --> DOOR_CLOSING : received move to message
DOOR_CLOSING --> MOVING : 1s elapsed
@enduml
